#!/usr/bin/env python3
"""Render docs/providers/model-catalog.md from the model_styles registry.

Mirrors the scripts/bump_manifests.py pattern: imports the registry, writes
the page, and is run by a CI step that diffs against the committed file to
guard against drift.

Usage:
    uv run python scripts/render_model_catalog.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running the script without `uv run` having added src/ to sys.path.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from image_generation_mcp.providers.model_styles import (  # noqa: E402
    CHECKPOINT_PATTERNS,
    MODEL_STYLES,
    StyleProfile,
)

DEFAULT_TARGET = ROOT / "docs" / "providers" / "model-catalog.md"

PROVIDERS_IN_ORDER: tuple[tuple[str, str], ...] = (
    ("openai", "OpenAI"),
    ("gemini", "Gemini"),
    ("placeholder", "Placeholder"),
)


def _profile_block(profile: StyleProfile) -> str:
    lifecycle_marker = (
        "" if profile.lifecycle == "current" else f" — **{profile.lifecycle}**"
    )
    note_line = f"\n> {profile.deprecation_note}\n" if profile.deprecation_note else ""
    return (
        f"### {profile.label}{lifecycle_marker}\n"
        f"{note_line}"
        f"\n**Best for:** {profile.style_hints}\n"
        f"\n**Avoid:** {profile.incompatible_styles}\n"
        f"\n**Good prompt:** `{profile.good_example}`\n"
        f"\n**Bad prompt:** `{profile.bad_example}`\n"
    )


def _render_provider_section(provider_key: str, provider_label: str) -> str:
    entries = sorted(
        (key, profile)
        for key, profile in MODEL_STYLES.items()
        if key.startswith(f"{provider_key}:")
    )
    if not entries:
        return ""

    lines = [f"## {provider_label}\n"]
    lines.append(
        f"Models exposed by the `{provider_key}` provider. Each model "
        f"resolves via exact-key lookup against the registry.\n"
    )
    lines.append("| Model ID | Label | Lifecycle |")
    lines.append("|----------|-------|-----------|")
    for key, profile in entries:
        model_id = key.split(":", 1)[1]
        lines.append(f"| `{model_id}` | {profile.label} | {profile.lifecycle} |")
    lines.append("")

    for _, profile in entries:
        lines.append(_profile_block(profile))

    return "\n".join(lines)


def _render_sd_section() -> str:
    lines = ["## SD WebUI\n"]
    lines.append(
        "SD WebUI checkpoints resolve via the regex-ordered "
        "`CHECKPOINT_PATTERNS` table. **First match wins** — patterns are "
        "ordered specific-before-generic, with an empty-pattern fallback "
        "as the final entry to guarantee a non-None match for every "
        "checkpoint name.\n"
    )

    lines.append("### Pattern catalog (in match order)\n")
    lines.append("| # | Pattern | Label |")
    lines.append("|---|---------|-------|")
    for idx, (pattern, profile) in enumerate(CHECKPOINT_PATTERNS, start=1):
        regex_display = (
            f"`{pattern.pattern}`" if pattern.pattern else "_(default fallback)_"
        )
        lines.append(f"| {idx} | {regex_display} | {profile.label} |")
    lines.append("")

    for pattern, profile in CHECKPOINT_PATTERNS:
        regex_display = (
            f"`{pattern.pattern}`"
            if pattern.pattern
            else "_(default fallback — empty pattern)_"
        )
        lines.append(f"#### Pattern: {regex_display}\n")
        lines.append(_profile_block(profile))

    return "\n".join(lines)


def render_catalog() -> str:
    """Return the full model catalog markdown.

    Returns:
        A string containing the complete model catalog in Markdown format,
        ready to be written to ``docs/providers/model-catalog.md``.
    """
    parts = [
        "<!-- Generated by scripts/render_model_catalog.py — do not edit. -->\n",
        "# Model Catalog\n",
        (
            "Per-model narrative metadata read by LLMs when choosing "
            "between providers and models. Closed-list providers "
            "(`openai`, `gemini`, `placeholder`) use exact-key lookup "
            "against `MODEL_STYLES`. SD WebUI uses the regex-ordered "
            "`CHECKPOINT_PATTERNS` table.\n"
        ),
        (
            "Source: "
            "`src/image_generation_mcp/providers/model_styles.py`. "
            "Regenerate with "
            "`uv run python scripts/render_model_catalog.py`.\n"
        ),
    ]
    for key, label in PROVIDERS_IN_ORDER:
        parts.append(_render_provider_section(key, label))
    parts.append(_render_sd_section())
    return "\n".join(parts).rstrip() + "\n"


def write_catalog(target: Path = DEFAULT_TARGET) -> None:
    """Render the catalog and write it to *target*.

    Args:
        target: Destination path for the generated Markdown file.
            Defaults to ``docs/providers/model-catalog.md`` relative to
            the repository root.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_catalog(), encoding="utf-8")


if __name__ == "__main__":
    write_catalog()
    print(f"Wrote {DEFAULT_TARGET}")
